#
#Fri Jun 19 17:12:01 GMT-05:00 2026
acceptInsecureCerts=false
browserName=chrome
goog\:chromeOptions={args\=[remote-allow-origins\=*, --disable-gpu --no-sandbox --disable-dev-shm-usage --remote-allow-origins\=*], extensions\=[]}
